from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from typing import Dict, List, Mapping, Protocol

from .models import ProofCandidate


class ProviderError(RuntimeError):
    pass


class CandidateProvider(Protocol):
    name: str
    model: str

    def generate_candidates(self, context: Dict[str, object]) -> List[ProofCandidate]:
        ...


class ChatCompletionsProvider:
    name = "chat_completions"
    api_key_name = ""
    model_name = ""
    base_url_name = ""
    default_base_url = ""

    def __init__(
        self,
        model: str = "",
        api_key: str | None = None,
        base_url: str | None = None,
        environ: Mapping[str, str] = os.environ,
    ) -> None:
        self.model = model or environ.get(self.model_name, "")
        self.api_key = api_key or environ.get(self.api_key_name, "")
        self.base_url = (base_url or environ.get(self.base_url_name, self.default_base_url)).rstrip("/")
        if not self.api_key:
            raise ProviderError(f"{self.api_key_name} is not configured")
        if not self.model:
            raise ProviderError(f"{self.model_name} is not configured")

    def generate_candidates(self, context: Dict[str, object]) -> List[ProofCandidate]:
        candidate_count = max(1, min(int(context.get("candidate_count", 1) or 1), 5))
        search_strategy = str(context.get("search_strategy") or "beam")
        proof_prefix = str(context.get("proof_prefix") or "")
        instruction = (
            "Return only the next Lean tactic line or short tactic block to append to the current proof prefix. "
            "Each API choice should contain one branch expansion."
            if search_strategy == "mcts"
            else "Return only a Lean tactic proof body for this theorem. Each API choice should contain one candidate proof body."
        )
        prompt = (
            f"{instruction}\n\n"
            f"Imports:\n{context.get('imports', '')}\n\n"
            f"Statement:\n{context.get('statement', '')}\n\n"
            f"Initial Lean goal state:\n{context.get('goal_state', '')}\n\n"
            f"Current proof prefix:\n{proof_prefix}\n\n"
            f"Recent Lean errors:\n{context.get('errors', [])}"
        )
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": "You write concise Lean 4 proof bodies."},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.2,
            "n": candidate_count,
        }
        request = urllib.request.Request(
            f"{self.base_url}/chat/completions",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=45) as response:
                data = json.loads(response.read().decode("utf-8"))
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            raise ProviderError(f"Provider request failed: {exc}") from exc
        candidates = []
        for choice in data.get("choices", [])[:candidate_count]:
            content = choice["message"]["content"].strip()
            candidates.append(ProofCandidate(proof=_strip_fences(content), rationale=f"Generated by {self.name} provider."))
        return candidates


class OpenAIProvider(ChatCompletionsProvider):
    name = "openai"
    api_key_name = "OPENAI_API_KEY"
    model_name = "OPENAI_MODEL"
    base_url_name = "OPENAI_BASE_URL"
    default_base_url = "https://api.openai.com/v1"


class MistralProvider(ChatCompletionsProvider):
    name = "mistral"
    api_key_name = "MISTRAL_API_KEY"
    model_name = "MISTRAL_MODEL"
    base_url_name = "MISTRAL_BASE_URL"
    default_base_url = "https://api.mistral.ai/v1"


def _strip_fences(text: str) -> str:
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        return "\n".join(lines).strip()
    return text


def provider_options(environ: Mapping[str, str] = os.environ) -> List[Dict[str, object]]:
    openai_model = environ.get("OPENAI_MODEL", "")
    options: List[Dict[str, object]] = [
        {
            "name": "openai",
            "label": _provider_label("OpenAI", openai_model),
            "model": openai_model,
            "configured": bool(environ.get("OPENAI_API_KEY") and openai_model),
        }
    ]
    if environ.get("MISTRAL_API_KEY"):
        mistral_model = environ.get("MISTRAL_MODEL", "")
        options.append(
            {
                "name": "mistral",
                "label": _provider_label("Mistral", mistral_model),
                "model": mistral_model,
                "configured": bool(mistral_model),
            }
        )
    return options


def _provider_label(name: str, model: str) -> str:
    return f"{name} ({model})" if model else name


def get_provider(name: str, model: str = "", environ: Mapping[str, str] = os.environ) -> CandidateProvider:
    if name == "openai":
        return OpenAIProvider(model=model, environ=environ)
    if name == "mistral":
        return MistralProvider(model=model, environ=environ)
    raise ProviderError(f"Unknown provider {name!r}")
