from rcc8.relations import ALL_RELATIONS


UNIVERSAL = set(ALL_RELATIONS)

COMPOSE = {
    "DC": {
        "DC": UNIVERSAL,
        "EC": {"DC", "EC", "PO", "TPP", "NTPP"},
        "PO": {"DC", "EC", "PO", "TPP", "NTPP"},
        "TPP": {"DC", "EC", "PO", "TPP", "NTPP"},
        "NTPP": {"DC", "EC", "PO", "TPP", "NTPP"},
        "TPPI": {"DC"},
        "NTPPI": {"DC"},
        "EQ": {"DC"},
    },
    "EC": {
        "DC": {"DC", "EC", "PO", "TPPI", "NTPPI"},
        "EC": {"DC", "EC", "PO", "TPP", "TPPI", "EQ"},
        "PO": {"DC", "EC", "PO", "TPP", "NTPP"},
        "TPP": {"EC", "PO", "TPP", "NTPP"},
        "NTPP": {"PO", "TPP", "NTPP"},
        "TPPI": {"DC", "EC"},
        "NTPPI": {"DC"},
        "EQ": {"EC"},
    },
    "PO": {
        "DC": {"DC", "EC", "PO", "TPPI", "NTPPI"},
        "EC": {"DC", "EC", "PO", "TPPI", "NTPPI"},
        "PO": UNIVERSAL,
        "TPP": {"PO", "TPP", "NTPP"},
        "NTPP": {"PO", "TPP", "NTPP"},
        "TPPI": {"DC", "EC", "PO", "TPPI", "NTPPI"},
        "NTPPI": {"DC", "EC", "PO", "TPPI", "NTPPI"},
        "EQ": {"PO"},
    },
    "TPP": {
        "DC": {"DC"},
        "EC": {"DC", "EC"},
        "PO": {"DC", "EC", "PO", "TPP", "NTPP"},
        "TPP": {"TPP", "NTPP"},
        "NTPP": {"NTPP"},
        "TPPI": {"DC", "EC", "PO", "TPP", "TPPI", "EQ"},
        "NTPPI": {"DC", "EC", "PO", "TPPI", "NTPPI"},
        "EQ": {"TPP"},
    },
    "NTPP": {
        "DC": {"DC"},
        "EC": {"DC"},
        "PO": {"DC", "EC", "PO", "TPP", "NTPP"},
        "TPP": {"NTPP"},
        "NTPP": {"NTPP"},
        "TPPI": {"DC", "EC", "PO", "TPP", "NTPP"},
        "NTPPI": UNIVERSAL,
        "EQ": {"NTPP"},
    },
    "TPPI": {
        "DC": {"DC", "EC", "PO", "TPPI", "NTPPI"},
        "EC": {"EC", "PO", "TPPI", "NTPPI"},
        "PO": {"PO", "TPPI", "NTPPI"},
        "TPP": {"PO", "TPP", "TPPI", "EQ"},
        "NTPP": {"PO", "TPP", "NTPP"},
        "TPPI": {"TPPI", "NTPPI"},
        "NTPPI": {"NTPPI"},
        "EQ": {"TPPI"},
    },
    "NTPPI": {
        "DC": {"DC", "EC", "PO", "TPPI", "NTPPI"},
        "EC": {"PO", "TPPI", "NTPPI"},
        "PO": {"PO", "TPPI", "NTPPI"},
        "TPP": {"PO", "TPPI", "NTPPI"},
        "NTPP": {"PO", "TPP", "NTPP", "TPPI", "NTPPI", "EQ"},
        "TPPI": {"NTPPI"},
        "NTPPI": {"NTPPI"},
        "EQ": {"NTPPI"},
    },
    "EQ": {
        "DC": {"DC"},
        "EC": {"EC"},
        "PO": {"PO"},
        "TPP": {"TPP"},
        "NTPP": {"NTPP"},
        "TPPI": {"TPPI"},
        "NTPPI": {"NTPPI"},
        "EQ": {"EQ"},
    },
}